name: Upload to Itch
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: itchyny/butler-action@v1
        with:
          user: moderatedan
          game: numcrunch
          channel: linux
          directory: NumCrunch_Release
        env:
          ITCH_API_KEY: ${{ gvFPsS8DbK60x4WOX1zNCGqfuet2moqXWmfeqO8V }}
